apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-config
  # namespace: default
  labels:
    environment: development
    app: express
data:
  port: "30080"
  database_url: mongodb-service
  # database_url: "mongodb://root:example@mongo-service.default.svc.cluster.local:27017"
