apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    environment: development
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            # - name: ME_CONFIG_MONGODB_AUTH_DATABASE
            #   value: "db"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "root"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "example"
            - name: ME_CONFIG_MONGODB_URL
              value: mongo-service
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    environment: development
    app: mongo-express-service
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
